version: '2'
services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile.notebook
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/code

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: --secure-file-priv=""
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
      - ./db:/var/lib/db_files

  gateway:
    build: .
    ports:
      - "9001:8888"
    volumes:
      - .:/code
    links:
      - db
    depends_on:
      - db
