# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
FROM jupyter/all-spark-notebook:15a66513da30

EXPOSE 8888

# Install Kernel Gateway and modules
RUN pip install jupyter_kernel_gateway
RUN pip install mysql-connector-python

ADD metrics_api.ipynb /srv/notebooks/
